kind: pipeline
type: kubernetes
name: add-server-ci

platform:
  os: linux
  arch: amd64

x-build-docker-image: &x-build-docker-image
  image: plugins/docker
  settings:
    custom_labels:
    - 'BUILD_NUMBER=${DRONE_BUILD_NUMBER}'
    - 'BUILD_SHA=${DRONE_COMMIT_SHA}'
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
  - main
  event:
    include:
    - push
    - pull_request

steps:
- name: test
  pull: if-not-exists
  image: golang:1.15.2
  commands:
  - cd src
  - go mod download
  - go test -v ./...
- name: build-image
  <<: *x-build-docker-image
  settings:
    repo: seifrajhi/ci-cd-demo-gitops
    dockerfile: src/Dockerfile
    context: src
  depends_on:
    - test
- name: update-manifests
  pull: if-not-exists
  image: rajhisaifeddine/kustomize-manifests:latest
  environment:
    SSH_KEY:
      from_secret: ssh_key
    IMAGES: rajhisaifeddine/ci-cd-gitops
    IMAGE_TAG: ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    MANIFEST_HOST: github.com
    MANIFEST_USER: seifrajhi
    MANIFEST_USER_EMAIL: rajhiseif@gmail.com
    MANIFEST_REPO: ci-cd-demo-manifests
    MANIFEST_BRANCH: main
    KUSTOMIZATION: production
  depends_on:
    - build-image
  when:
    event: push